### Verify api key and get session
GET http://localhost:4000/api/v1/verify HTTP/1.1
content-type: application/json
api-key: 1fI4SxneQu26epS9hNVH9OEyVwwTyAH5V71i4DUJkSG6GaG66NPOfjMWh6rm1c0b
# Api-Key: someapikey

## Response Type
# {
#   "session_id": "IqU58+ZJoP0TAVgmZDEPa9GtPGry0vgUCuocV+PtlBFULkowOzFplZuDthVcU4bLBVPiU4oRaLCQyFPz8DbTbg==",
#   "message": "Session verified"
# }

## Error Response
# {
#   "statusCode": 400,
#   "message": "Api Key is missing"
# }

## Error Response
# {
#   "statusCode": 404,
#   "message": "API Key not found"
# }


### Verify api key and get session
GET http://localhost:4000/status HTTP/1.1
content-type: application/json


### Post Event to the session
POST http://localhost:4000/api/v1/events?session_id=CYSHEkeJGYC3BlkkeACMHEGFm5fb4PKncbopa29KEoIHEY5/Ms6g1pXW+3Iv8de6sITNN5poKyF3Hgy/RVigwQ== HTTP/1.1
content-type: application/json
Api-Key: 1fI4SxneQu26epS9hNVH9OEyVwwTyAH5V71i4DUJkSG6GaG66NPOfjMWh6rm1c0b1

{
  "data": [
    [],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 499.08984375,
            "clientY": 314.8125,
            "ctrlKey": false,
            "layerX": 390,
            "layerY": 36,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 366.08984375,
            "offsetY": 28.8125,
            "pageX": 499.08984375,
            "pageY": 314.8125,
            "pointerType": "mouse",
            "screenX": 499.08984375,
            "screenY": 426.8125,
            "shiftKey": false,
            "x": 499.08984375,
            "y": 314.8125,
            "timestamp": 1721847757700
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 493.7265625,
            "clientY": 339.65234375,
            "ctrlKey": false,
            "layerX": 384,
            "layerY": 61,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 360.7265625,
            "offsetY": 53.65234375,
            "pageX": 493.7265625,
            "pageY": 339.65234375,
            "pointerType": "mouse",
            "screenX": 493.7265625,
            "screenY": 451.65234375,
            "shiftKey": false,
            "x": 493.7265625,
            "y": 339.65234375,
            "timestamp": 1721847758249
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 417.6796875,
            "clientY": 330.2578125,
            "ctrlKey": false,
            "layerX": 308,
            "layerY": 52,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 284.6796875,
            "offsetY": 44.2578125,
            "pageX": 417.6796875,
            "pageY": 330.2578125,
            "pointerType": "mouse",
            "screenX": 417.6796875,
            "screenY": 442.2578125,
            "shiftKey": false,
            "x": 417.6796875,
            "y": 330.2578125,
            "timestamp": 1721847758733
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 372.87109375,
            "clientY": 391.90234375,
            "ctrlKey": false,
            "layerX": 372,
            "layerY": 391,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 372.87109375,
            "offsetY": 391.90234375,
            "pageX": 372.87109375,
            "pageY": 391.90234375,
            "pointerType": "mouse",
            "screenX": 372.87109375,
            "screenY": 503.90234375,
            "shiftKey": false,
            "x": 372.87109375,
            "y": 391.90234375,
            "timestamp": 1721847759233
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 453.8515625,
            "clientY": 521.30078125,
            "ctrlKey": false,
            "layerX": 453,
            "layerY": 521,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 453.8515625,
            "offsetY": 521.30078125,
            "pageX": 453.8515625,
            "pageY": 521.30078125,
            "pointerType": "mouse",
            "screenX": 453.8515625,
            "screenY": 633.30078125,
            "shiftKey": false,
            "x": 453.8515625,
            "y": 521.30078125,
            "timestamp": 1721847759715
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 382.98828125,
            "clientY": 328.6171875,
            "ctrlKey": false,
            "layerX": 273,
            "layerY": 50,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 249.98828125,
            "offsetY": 42.6171875,
            "pageX": 382.98828125,
            "pageY": 328.6171875,
            "pointerType": "mouse",
            "screenX": 382.98828125,
            "screenY": 440.6171875,
            "shiftKey": false,
            "x": 382.98828125,
            "y": 328.6171875,
            "timestamp": 1721847760217
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 471.1484375,
            "clientY": 140.08203125,
            "ctrlKey": false,
            "layerX": 471,
            "layerY": 140,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 471.1484375,
            "offsetY": 140.08203125,
            "pageX": 471.1484375,
            "pageY": 140.08203125,
            "pointerType": "mouse",
            "screenX": 471.1484375,
            "screenY": 252.08203125,
            "shiftKey": false,
            "x": 471.1484375,
            "y": 140.08203125,
            "timestamp": 1721847760699
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 586.28125,
            "clientY": 145.625,
            "ctrlKey": false,
            "layerX": 586,
            "layerY": 145,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 586.28125,
            "offsetY": 145.625,
            "pageX": 586.28125,
            "pageY": 145.625,
            "pointerType": "mouse",
            "screenX": 586.28125,
            "screenY": 257.625,
            "shiftKey": false,
            "x": 586.28125,
            "y": 145.625,
            "timestamp": 1721847761233
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 223.05859375,
            "clientY": 61.19921875,
            "ctrlKey": false,
            "layerX": 90,
            "layerY": 45,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 66.05859375,
            "offsetY": 30.44921875,
            "pageX": 223.05859375,
            "pageY": 61.19921875,
            "pointerType": "mouse",
            "screenX": 223.05859375,
            "screenY": 173.19921875,
            "shiftKey": false,
            "x": 223.05859375,
            "y": 61.19921875,
            "timestamp": 1721847761984
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847762648
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847762867
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763014
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763184
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763367
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763551
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763733
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763901
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847764068
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847764250
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 564.51953125,
            "clientY": 489.3984375,
            "ctrlKey": false,
            "layerX": 564,
            "layerY": 489,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 564.51953125,
            "offsetY": 489.3984375,
            "pageX": 564.51953125,
            "pageY": 489.3984375,
            "pointerType": "mouse",
            "screenX": 564.51953125,
            "screenY": 601.3984375,
            "shiftKey": false,
            "x": 564.51953125,
            "y": 489.3984375,
            "timestamp": 1721847769516
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 564.51953125,
            "clientY": 489.3984375,
            "ctrlKey": false,
            "layerX": 564,
            "layerY": 489,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 564.51953125,
            "offsetY": 489.3984375,
            "pageX": 564.51953125,
            "pageY": 489.3984375,
            "pointerType": "mouse",
            "screenX": 564.51953125,
            "screenY": 601.3984375,
            "shiftKey": false,
            "x": 564.51953125,
            "y": 489.3984375,
            "timestamp": 1721847769783
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770200
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770366
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770501
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770684
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770834
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770984
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847771150
        }
    ]
]
}


### Post Event to the session
POST http://localhost:4000/api/v1/events?session_id=nvbx439TqxBs1GMf5F1cWwgAAa7k9LUIYvWB1LvCpmGQMSYLsn3ecNhw6dCnk7AAgItDpSsNNICoLqbASSsA HTTP/1.1
content-type: application/json
Api-Key: 1fI4SxneQu26epS9hNVH9OEyVwwTyAH5V71i4DUJkSG6GaG66NPOfjMWh6rm1c0b

{
  "data": [
    [],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 499.08984375,
            "clientY": 314.8125,
            "ctrlKey": false,
            "layerX": 390,
            "layerY": 36,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 366.08984375,
            "offsetY": 28.8125,
            "pageX": 499.08984375,
            "pageY": 314.8125,
            "pointerType": "mouse",
            "screenX": 499.08984375,
            "screenY": 426.8125,
            "shiftKey": false,
            "x": 499.08984375,
            "y": 314.8125,
            "timestamp": 1721847757700
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 493.7265625,
            "clientY": 339.65234375,
            "ctrlKey": false,
            "layerX": 384,
            "layerY": 61,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 360.7265625,
            "offsetY": 53.65234375,
            "pageX": 493.7265625,
            "pageY": 339.65234375,
            "pointerType": "mouse",
            "screenX": 493.7265625,
            "screenY": 451.65234375,
            "shiftKey": false,
            "x": 493.7265625,
            "y": 339.65234375,
            "timestamp": 1721847758249
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 417.6796875,
            "clientY": 330.2578125,
            "ctrlKey": false,
            "layerX": 308,
            "layerY": 52,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 284.6796875,
            "offsetY": 44.2578125,
            "pageX": 417.6796875,
            "pageY": 330.2578125,
            "pointerType": "mouse",
            "screenX": 417.6796875,
            "screenY": 442.2578125,
            "shiftKey": false,
            "x": 417.6796875,
            "y": 330.2578125,
            "timestamp": 1721847758733
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 372.87109375,
            "clientY": 391.90234375,
            "ctrlKey": false,
            "layerX": 372,
            "layerY": 391,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 372.87109375,
            "offsetY": 391.90234375,
            "pageX": 372.87109375,
            "pageY": 391.90234375,
            "pointerType": "mouse",
            "screenX": 372.87109375,
            "screenY": 503.90234375,
            "shiftKey": false,
            "x": 372.87109375,
            "y": 391.90234375,
            "timestamp": 1721847759233
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 453.8515625,
            "clientY": 521.30078125,
            "ctrlKey": false,
            "layerX": 453,
            "layerY": 521,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 453.8515625,
            "offsetY": 521.30078125,
            "pageX": 453.8515625,
            "pageY": 521.30078125,
            "pointerType": "mouse",
            "screenX": 453.8515625,
            "screenY": 633.30078125,
            "shiftKey": false,
            "x": 453.8515625,
            "y": 521.30078125,
            "timestamp": 1721847759715
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 382.98828125,
            "clientY": 328.6171875,
            "ctrlKey": false,
            "layerX": 273,
            "layerY": 50,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 249.98828125,
            "offsetY": 42.6171875,
            "pageX": 382.98828125,
            "pageY": 328.6171875,
            "pointerType": "mouse",
            "screenX": 382.98828125,
            "screenY": 440.6171875,
            "shiftKey": false,
            "x": 382.98828125,
            "y": 328.6171875,
            "timestamp": 1721847760217
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 471.1484375,
            "clientY": 140.08203125,
            "ctrlKey": false,
            "layerX": 471,
            "layerY": 140,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 471.1484375,
            "offsetY": 140.08203125,
            "pageX": 471.1484375,
            "pageY": 140.08203125,
            "pointerType": "mouse",
            "screenX": 471.1484375,
            "screenY": 252.08203125,
            "shiftKey": false,
            "x": 471.1484375,
            "y": 140.08203125,
            "timestamp": 1721847760699
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 586.28125,
            "clientY": 145.625,
            "ctrlKey": false,
            "layerX": 586,
            "layerY": 145,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 586.28125,
            "offsetY": 145.625,
            "pageX": 586.28125,
            "pageY": 145.625,
            "pointerType": "mouse",
            "screenX": 586.28125,
            "screenY": 257.625,
            "shiftKey": false,
            "x": 586.28125,
            "y": 145.625,
            "timestamp": 1721847761233
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 223.05859375,
            "clientY": 61.19921875,
            "ctrlKey": false,
            "layerX": 90,
            "layerY": 45,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 66.05859375,
            "offsetY": 30.44921875,
            "pageX": 223.05859375,
            "pageY": 61.19921875,
            "pointerType": "mouse",
            "screenX": 223.05859375,
            "screenY": 173.19921875,
            "shiftKey": false,
            "x": 223.05859375,
            "y": 61.19921875,
            "timestamp": 1721847761984
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847762648
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847762867
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763014
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763184
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763367
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763551
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763733
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847763901
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847764068
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 206.44140625,
            "clientY": 155.0625,
            "ctrlKey": false,
            "layerX": 206,
            "layerY": 155,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 206.44140625,
            "offsetY": 155.0625,
            "pageX": 206.44140625,
            "pageY": 155.0625,
            "pointerType": "mouse",
            "screenX": 206.44140625,
            "screenY": 267.0625,
            "shiftKey": false,
            "x": 206.44140625,
            "y": 155.0625,
            "timestamp": 1721847764250
        }
    ],
    [
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 564.51953125,
            "clientY": 489.3984375,
            "ctrlKey": false,
            "layerX": 564,
            "layerY": 489,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 564.51953125,
            "offsetY": 489.3984375,
            "pageX": 564.51953125,
            "pageY": 489.3984375,
            "pointerType": "mouse",
            "screenX": 564.51953125,
            "screenY": 601.3984375,
            "shiftKey": false,
            "x": 564.51953125,
            "y": 489.3984375,
            "timestamp": 1721847769516
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 564.51953125,
            "clientY": 489.3984375,
            "ctrlKey": false,
            "layerX": 564,
            "layerY": 489,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 564.51953125,
            "offsetY": 489.3984375,
            "pageX": 564.51953125,
            "pageY": 489.3984375,
            "pointerType": "mouse",
            "screenX": 564.51953125,
            "screenY": 601.3984375,
            "shiftKey": false,
            "x": 564.51953125,
            "y": 489.3984375,
            "timestamp": 1721847769783
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770200
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770366
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770501
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770684
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770834
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847770984
        },
        {
            "isTrusted": true,
            "altKey": false,
            "button": 0,
            "buttons": 0,
            "clientX": 574.48828125,
            "clientY": 294.71484375,
            "ctrlKey": false,
            "layerX": 465,
            "layerY": 16,
            "metaKey": false,
            "movementX": 0,
            "movementY": 0,
            "offsetX": 441.48828125,
            "offsetY": 8.71484375,
            "pageX": 574.48828125,
            "pageY": 294.71484375,
            "pointerType": "mouse",
            "screenX": 574.48828125,
            "screenY": 406.71484375,
            "shiftKey": false,
            "x": 574.48828125,
            "y": 294.71484375,
            "timestamp": 1721847771150
        }
    ]
]
}